### ISSUE TITLE
2.3 Requirements: Adviespaneel voor de simulatie

### ISSUE THREAD

**Issue by b-kuiper** [LutzenH/Project-Parkeergarage#19]
Probeer door middel van de van de informatie die je uit de simulator kunt halen een advies te formuleren voor de organisatie. Probeer bijvoorbeeld te controleren of het geplande reserveringsproces, waarbij vanaf een kwartier voor aanvang een plek gereserveerd
wordt altijd voldoende gereserveerde plaatsen oplevert.
Hierbij is het dus van belang dat de bezetting van de parkeergarage in de simulator een realistisch beeld geeft van de werkelijkheid.

**Comment by LutzenH** [comment]
1d6ad07e0cab93680c048e04cf886e0d78a52754
